name: test
on:
  push:
    tags:
      - v*
    branches: 
      - main
  pull_request:
    branches: 
      - main
jobs:

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Test
        run: go test ./... 
